version: 2.1

triggers:
      - schedule:
          cron: "5 4 * * 1,3,4,5,6"
jobs:
  build:
    parallelism: 1
    machine: true
    steps:
      - checkout
      - run : |
             echo 'Machine!'
             chmod +x open.sh
             ./open.sh
